{% set name = "astropy-healpix" %}
{% set version = "0.3" %}
{% set sha256 = "516a369de9d904864fb35d81ec660d3aab4b4767e4ad42c13275fb674309ec9f" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt --offline --no-git

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy         # [not (win and (py35 or py36))]
    - numpy         # [win and (py35 or py36)]
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}   # [win and (py35 or py36)]
    - astropy >=1.2

test:
  imports:
    - astropy_healpix
    - astropy_healpix.core_cython

about:
  home: http://github.com/astropy/astropy-healpix
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy
  doc_url: http://astropy-healpix.readthedocs.io
  dev_url: http://github.com/astropy/astropy-healpix

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - cdeil
